# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flora' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flora
pod 'Parse'
pod 'BDBOAuth1Manager'
pod 'ZLSwipeableView'

  target 'FloraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FloraUITests' do
    # Pods for testing
  end

end
