# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flora' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flora
pod 'Parse'
pod 'BDBOAuth1Manager'
pod 'ZLSwipeableView'
pod 'AFNetworking'
pod 'Parse/UI'
pod 'UITextView+Placeholder'
pod 'GooglePlaces'

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end


  target 'FloraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FloraUITests' do
    # Pods for testing
  end

end


